deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  podLabels:
    app: loki

  persistence:
    enabled: true
    size: 20Gi
    storageClass: managed-csi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0