apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: default-alerts
  namespace: monitoring
  labels:
    alertmanagerconfig: default
spec:
  route:
    receiver: default
    matchers:
      - name: alertname
        matchType: "="
        value: PortfolioTestAlert
  receivers:
    - name: default