apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  annotations:
    azure.workload.identity/client-id: "50c5b586-bc99-4540-9c89-80d55cc73ba8"
  labels:
    azure.workload.identity/use: "true"