apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  annotations:
    azure.workload.identity/client-id: "7f680af5-d26f-4e2f-b6ac-d9fdcf151dd4"
  labels:
    azure.workload.identity/use: "true"