apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  annotations:
    azure.workload.identity/client-id: "{{ .Values.backend.workloadIdentity.clientId }}"
  labels:
    azure.workload.identity/use: "true"