controller:
  type: daemonset

  podLabels:
    app: alloy

alloy:
  configMap:
    create: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

  configReloader:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 100Mi