apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "94400e7d-cf8f-40d2-885a-64bb68f06378"