apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-identity
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infra-project
  source:
    repoURL: https://github.com/Rehox0/allegro-analytics-eks.git
    targetRevision: testing
    path: k8s/gitops/infra/identity/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-ns
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
