apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: "Application project for ArgoCD"
  sourceRepos:
    - 'https://github.com/Rehox0/allegro-analytics-eks.git'
  destinations:
    - namespace: '*'
      server: '*'