apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra-project
  source:
    repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
    targetRevision: testing
    path: k8s/gitops/workloads/backend
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true