apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::563605821766:role/Multi-Cloud-Kubernetes-Platform-backend-irsa-role"