replicaCount: 3

image:
  repository: 563605821766.dkr.ecr.eu-central-1.amazonaws.com/multi-cloud-project-ecr-frontend
  tag: bfbaf4559e2d2651657b46eca00d5307706e7299

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

serviceAccount:
  create: true
  name: frontend

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000