replicaCount: 3

image:
  repository: multicloudprojectacr.azurecr.io/frontend
  tag: 642b8b17565fd3db7329a366048b80c6dca71b28

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

serviceAccount:
  create: true
  name: frontend

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000