replicaCount: 3

image:
  repository: multicloudprojectacr.azurecr.io/frontend
  tag: 2ab13be5dfffc411e3c08c25f2c870d18b7c53d9

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

serviceAccount:
  create: true
  name: frontend

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000