replicaCount: 3

image:
  repository: 134748917914.dkr.ecr.eu-north-1.amazonaws.com/portfolio-frontend
  tag: 40ab5e3a8abfa6eef61b6f5e41fd0506b255fb25

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

serviceAccount:
  create: true
  name: frontend

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000