replicaCount: 3

image:
  repository: acrmulticloudproject.azurecr.io/frontend
  tag: c4fd5ecd2835fcc52864d558f03fe32e8a232b55

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

serviceAccount:
  create: true
  name: frontend

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000