apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-0c11219423ce00ad3

  role: Multi-Cloud-Kubernetes-Platform-karpenter-node-role

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: Multi-Cloud-Kubernetes-Platform-eks-cluster

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: Multi-Cloud-Kubernetes-Platform-eks-cluster
  tags:
    Name: Multi-Cloud-Kubernetes-Platform-karpenter
    karpenter.sh/discovery: Multi-Cloud-Kubernetes-Platform-eks-cluster