apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    chart: cilium
    repoURL: 'https://helm.cilium.io/'
    targetRevision: 1.15.5
    helm:
      values: |
        eni:
          enabled: true
        ipam:
          mode: eni
        egressMasqueradeInterfaces: eth+
        cni:
          chainingMode: aws-cni
          exclusive: false
        routing-mode: native
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration