apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::134748917914:role/allegro-analytics-eks-dev-backend-irsa-role"