apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-backend-dev-secret
  namespace: backend-ns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: eso-backend-dev-secret
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: infra-project
      property: SECRET_KEY