crds:
  enabled: true

grafana:
  enabled: true
  priorityClassName: prio-medium
  admin:
    existingSecret: eso-grafana-secret
    userKey: grafana-admin-user
    passwordKey: grafana-admin-password
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.loki.svc.cluster.local:3100
      isDefault: false

prometheus:
  enabled: true
  prometheusSpec:
    priorityClassName: prio-medium

alertmanager:
  enabled: true
  alertmanagerSpec:
    priorityClassName: prio-medium

kubeStateMetrics:
  enabled: true
  priorityClassName: prio-medium

nodeExporter:
  enabled: true
  priorityClassName: prio-medium
