replicaCount: 4

image:
  repository: 563605821766.dkr.ecr.eu-central-1.amazonaws.com/multi-cloud-project-ecr-backend
  tag: 119f7525a38fa811eb1357d4c9ca3d59ee176da3

serviceAccount:
  create: false
  name: backend

env:
  debug: "True"
  allowedHosts: "*"
  cloudProvider: "AWS"
  cloudRegion: "eu-central-1"
  backendPlatform: "EKS"

service:
  type: ClusterIP
  port: 8000
  
  containerPort: 8000
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: UDP
    port: 9999
    targetPort: 9999
  
gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"


networkPolicy:
  enabled: true

externalSecret:
  refreshInterval: "1m"
  remoteKey: "multi-cloud-project-dev"
  targetName: "eso-backend-secret"
  secretStoreRef:
    name: "aws-secretsmanager"
    kind: "ClusterSecretStore"

provider:
  aws:
    region: eu-central-1

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000