replicaCount: 4

image:
  repository: multicloudprojectacr.azurecr.io/backend
  tag: 9da5531093bd756ece8b12c2b187d95b34b3518b

serviceAccount:
  create: false
  name: backend

env:
  debug: "True"
  allowedHosts: "*"

service:
  type: ClusterIP
  port: 8000
  
  containerPort: 8000
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: UDP
    port: 9999
    targetPort: 9999

gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"

externalSecret:
  refreshInterval: "1m"
  remoteKey: "Multi-Cloud-ProjectKV"
  targetName: "eso-backend-secret"
  secretStoreRef:
    name: "azure-keyvault"
    kind: "ClusterSecretStore"

networkPolicy:
  enabled: true

backend:
  host: http://workload-backend-dev.backend-ns.svc.cluster.local
  port: 8000