replicaCount: 1

image:
  repository: rehox0/portfolio-backend
  tag: latest

serviceAccount:
  create: true
  name: backend
  roleArn: "arn:aws:iam::111111111111:role/infra-project-dev-backend-irsa-role"

env:
  debug: "False"
  allowedHosts: "*"