replicaCount: 3

image:
  repository: rehox0/portfolio-backend
  tag: latest

serviceAccount:
  create: true
  name: backend
  roleArn: "arn:aws:iam::134748917914:role/allegro-analytics-eks-dev-backend-irsa-role"

env:
  debug: "True"
  allowedHosts: "*"

externalSecret:
  targetName: backend-secret

service:
  type: ClusterIP
  port: 8000
  
  containerPort: 8000
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: UDP
    port: 9999
    targetPort: 9999
  
gateway:
  enabled: true
  name: main-gateway
  namespace: gateway-ns
  host: "my-domain.com"


networkPolicy:
  enabled: true

externalSecret:
  refreshInterval: "1m"
  remoteKey: "infra-project"
  targetName: "backend-secret"
  secretStoreRef:
    name: "aws-secretsmanager"
    kind: "ClusterSecretStore"

provider:
  aws:
    region: eu-north-1