apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: eso-azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.spec.provider.azurekv.vaultUrl | quote }}
      tenantId: {{ .Values.spec.provider.azurekv.tenantId | quote }}
      serviceAccountRef:
        name: backend
        namespace: backend-ns