apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-project
  namespace: argocd
spec:
  description: "Application project for ArgoCD"
  sourceRepos:
    - 'https://kyverno.github.io/kyverno/'
    - 'https://charts.external-secrets.io'
    - 'https://github.com/Rehox0/allegro-analytics-eks.git'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-addons
  namespace: argocd

spec:
  template:
    metadata:
      name: 'default'
    spec:
      project: infra-project
      source:
        repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
        targetRevision: testing
        path: '.'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  generators:

    # ============================================================
    # GENERATOR 1 
    # ============================================================
    - list:
        elements:
          - name: backend-identity
            path: k8s/gitops/infra/identity/backend
            syncGroup: "1"
            namespace: backend-ns

          - name: eso-backend-secret
            path: k8s/gitops/infra/eso/backend_secret
            syncGroup: "2"
            namespace: external-secrets

          - name: gateway
            path: k8s/gitops/infra/gateway
            syncGroup: "3"
            namespace: gateway-ns

          - name: kyverno-policies
            path: k8s/gitops/infra/kyverno/policy
            syncGroup: "3"
            namespace: kyverno

        template:
          metadata:
            name: '{{name}}'
            labels:
              infra.project.dev/sync-group: '{{syncGroup}}'
          spec:
            project: infra-project
            source:
              repoURL: https://github.com/Rehox0/allegro-analytics-eks.git
              targetRevision: testing
              path: '{{path}}'
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{namespace}}'
            ignoreDifferences:
              - group: kyverno.io
                kind: ClusterPolicy
                jsonPointers:
                  - /spec/rules/0/skipBackgroundRequests
                  - /spec/rules/0/validate/allowExistingViolations
                  - '.spec.rules[] | select(.name == "infra-project") | .generate'
            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

    # ============================================================
    # GENERATOR 2
    # ============================================================
    - list:
        elements:

          - name: workload-backend-dev
            path: k8s/gitops/workloads/backend
            valuesFile: values-dev.yaml
            syncGroup: "3"
            namespace: backend-ns

          - name: workload-frontend-dev
            path: k8s/gitops/workloads/frontend
            valuesFile: values-dev.yaml
            syncGroup: "4"
            namespace: frontend-ns

        template:
          metadata:
            name: '{{name}}'
            labels:
              infra.project.dev/sync-group: '{{syncGroup}}'

          spec:
            project: infra-project

            source:
              repoURL: https://github.com/Rehox0/allegro-analytics-eks.git
              targetRevision: testing
              path: '{{path}}'
              helm:
                valueFiles:
                  - '{{valuesFile}}'

            destination:
              server: https://kubernetes.default.svc
              namespace: '{{namespace}}'

            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

    - list:
        elements:

          - name: eso-operator
            syncGroup: "1"
            namespace: external-secrets
            repoURL: https://charts.external-secrets.io
            chart: external-secrets
            targetRevision: "2.8.0"

          - name: kyverno-system
            syncGroup: "1"
            namespace: kyverno
            repoURL: https://kyverno.github.io/kyverno/
            chart: kyverno
            targetRevision: "3.8.2"

        template:
          metadata:
            name: '{{name}}'
            labels:
              infra.project.dev/sync-group: '{{syncGroup}}'

          spec:
            project: infra-project

            source:
              repoURL: '{{repoURL}}'
              chart: '{{chart}}'
              targetRevision: '{{targetRevision}}'
              helm:
                values: |
                  installCRDs: true

            destination:
              server: https://kubernetes.default.svc
              namespace: '{{namespace}}'

            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

  # ================================================================
  # RollingSync
  # ================================================================

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      # GROUP 1
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["1"]
      # GROUP 2
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["2"]
      # GROUP 3
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["3"]
      # GROUP 4
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["4"]