apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-project
  namespace: argocd
spec:
  description: "Application project for ArgoCD"
  sourceRepos:
    - 'https://kyverno.github.io/kyverno/'
    - 'https://charts.external-secrets.io'
    - 'https://github.com/Rehox0/allegro-analytics-eks.git'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-addons
  namespace: argocd

spec:
  template:
    metadata:
      name: 'default'
    spec:
      project: infra-project
      source:
        repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
        targetRevision: testing
        path: '.'
      destination:
        server: https://kubernetes.default.svc
        namespace: default

  generators:
    - list:
        elements:

          # ============================================================
          # GROUP 2
          # ClusterSecretStore-backend-dev
          # ============================================================

          - name: eso-secret-storage
            path: k8s/gitops/infra/eso/cluster_secret_store
            syncGroup: "2"
            namespace: external-secrets

          # ============================================================
          # GROUP 3
          # Workloads / remaining infrastructure
          # ============================================================

          - name: workload-backend-dev
            path: k8s/gitops/workloads/backend/app
            syncGroup: "3"
            namespace: backend-ns

          - name: gateway
            path: k8s/gitops/infra/gateway/app
            syncGroup: "3"
            namespace: gateway-ns


          - name: kyverno-policies
            repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
            targetRevision: testing
            path: k8s/gitops/infra/kyverno/policy/app
            syncGroup: "3"
            namespace: kyverno

          # ============================================================
          # GROUP 4
          # Workloads / testing
          # ============================================================

          - name: workload-frontend-dev
            repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
            targetRevision: testing
            path: k8s/gitops/workloads/frontend/app
            syncGroup: "4"
            namespace: frontend-ns

        template:
          metadata:
            name: '{{name}}'
            labels:
              infra.project.dev/sync-group: '{{syncGroup}}'
          spec:
            project: infra-project
            source:
              repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
              targetRevision: testing
              path: '{{path}}'
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{namespace}}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

    # -----------------------------------------------------------------
    # GENERATOR 2
    # -----------------------------------------------------------------
    - list:
        elements:
          - name: eso-operator
            repoURL: 'https://charts.external-secrets.io'
            chart: external-secrets
            targetRevision: '0.14.2'
            syncGroup: "1"
            namespace: external-secrets

          - name: kyverno-system
            repoURL: 'https://kyverno.github.io/kyverno/'
            chart: kyverno
            targetRevision: '3.2.5'
            syncGroup: "3"
            namespace: kyverno

        template:
          metadata:
            name: '{{name}}'
            labels:
              infra.project.dev/sync-group: '{{syncGroup}}'
          spec:
            project: infra-project
            source:
              repoURL: '{{repoURL}}'
              chart: '{{chart}}'
              targetRevision: '{{targetRevision}}'
              helm:
                values: |
                  installCRDs: true
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{namespace}}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
  # ================================================================
  # RollingSync
  # ================================================================

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      # GROUP 1
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["1"]
      # GROUP 2
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["2"]
      # GROUP 3
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["3"]
      # GROUP 4
      - matchExpressions:
          - key: infra.project.dev/sync-group
            operator: In
            values: ["4"]