apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rehox0/allegro-analytics-eks.git'
    targetRevision: testing
    path: k8s/gitops/infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/spec/containers/0/env
      - group: cert-manager.io
        kind: Certificate
        jsonPointers:
          - /spec/duration