apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: infra-project
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.9.1
    helm:
      values: |
        settings:
          clusterName: Multi-Cloud-Kubernetes-Platform-eks-cluster
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::134748917914:role/Multi-Cloud-Kubernetes-Platform-karpenter-controller-role
        priorityClassName: prio-critical
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true