apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-workload-backend-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: aws-infra-project

  source:
    repoURL: https://github.com/Rehox0/Multi-Cloud-Kubernetes-Platform.git
    targetRevision: testing
    path: k8s/gitops/workloads/backend
    helm:
      valueFiles:
        - aws-values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true