apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-backend-secret-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra-project

  source:
    repoURL: https://github.com/Rehox0/allegro-analytics-eks.git
    targetRevision: testing
    path: k8s/gitops/infra/eso/cluster_secret_store/backend_secret

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true