apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Release.Namespace }}