apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Release.Name }}-migrate-
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrate
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    spec:
      restartPolicy: Never
      priorityClassName: prio-high
      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          command:
            - python
            - manage.py
            - migrate
            - --noinput

          env:
            - name: DEBUG
              value: {{ .Values.env.debug | quote }}

            - name: ALLOWED_HOSTS
              value: {{ .Values.env.allowedHosts | quote }}

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: SECRET_KEY

            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: POSTGRES_PORT

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetName }}
                  key: POSTGRES_PASSWORD
                  
            - name: POSTGRES_FALLBACK_IP
              valueFrom:
                secretKeyRef:
                  name: postgres-fallback-secret
                  key: POSTGRES_FALLBACK_IP

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL