apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range .Values.service.ports }}
        - name: {{ .protocol | lower }}
          protocol: {{ .protocol }}
          port: {{ .port }}
          targetPort: {{ .targetPort }}
        {{- end }}
      