apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-discord-alertmanager-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: eso-azure-keyvault
    kind: ClusterSecretStore

  target:
    name: eso-discord-alertmanager-webhook
    creationPolicy: Owner

  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord-alertmanager-webhook