apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-backend-secret
  namespace: backend-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-azure-keyvault
    kind: ClusterSecretStore
  target:
    name: eso-backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: django-secret-key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: POSTGRES_HOST
      remoteRef:
        key: postgresql-host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: POSTGRES_PORT
      remoteRef:
        key: postgresql-port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgresql-database
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgresql-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgresql-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None