apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-grafana-sercet
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-azure-keyvault
    kind: ClusterSecretStore

  target:
    name: eso-grafana-secret
    creationPolicy: Owner

  data:
    - secretKey: grafana-admin-password
      remoteRef:
        key: grafana-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None